### ISSUE TITLE
Unable connect to wifi network

### ISSUE THREAD

**Issue by STableThink** [sharandac/powermeter#5]
When trying to connect to my own personal wifi ap (and other test access points), the debug console only shows this error at startup:
``` 
scan for SSID "stsopenwrt" ... found
connect to stsopenwrt (****)
WiFi lost, restart ... failed
starting Wifi-AP with SSID "powermeter1"
```
So the esp is unable to log into my home network.
Best regards
Jonas

**Comment by sharandac** [comment]
Thanks for your feedback. I have also seen this error from time to time. The ESP32 will probably connect correctly to your network later when your settings are right. With Firefox, you can then connect to "http://powermeter1.local" without knowing the IP.

"powermeter1" is your Wifi AP SSID in this case.

Otherwise, let me know ...
