### ISSUE TITLE
Question: Precision for 3phase setup?

### ISSUE THREAD

**Issue by gytisgreitai** [sharandac/powermeter#8]
Hi, thanks for the nice write up and detailed diagram! I have a bit offtopic question, how precise do you find the readings of these clamps without voltage measuring? I’m contemplating about using this diy vs buying ready made product like shelly. Do you calibrate them somehow?

**Comment by sharandac** [comment]
Thank you for your feedback. The square-root measurement method is quite accurate, even if the ADC is not. Just like the SCT-013-0x0 converters. But that's not a problem if you have a consumer from which you know the exact power consumption. With this, you can calibrate everything precisely.
I have an exact 2kW consumer that has been precisely measured for me.
I get +/-0.5 % accuracy with 2kW. Of course, as with all measuring methods, it becomes less accurate in the lower range.
The voltage can also be measured using the same method (small 9 V transformer or [link](https://www.amazon.de/gp/product/B08ZDQ77ZC/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1)) and then calculated. Or you can simply enter 230 or 110 volts.
I also recommend using the experimental branch, which works better but is not yet completely finished because I lack some time.
